name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build completed"
          echo "Contents of out directory:"
          ls -la out/
        env:
          NODE_ENV: production

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true
          clean-exclude: |
            .nojekyll
          single-commit: true
          git-config-name: GitHub Actions
          git-config-email: actions@github.com

      - name: Create .nojekyll file
        run: |
          cd out
          touch .nojekyll
          echo "Created .nojekyll file"

      - name: Verify deployment
        run: |
          echo "Deployment completed"
          echo "Checking gh-pages branch..."
          git fetch origin gh-pages
          git checkout gh-pages
          ls -la 